// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lonkikskaonijlapdyjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvbmtpa3NrYW9uaWpsYXBkeWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjM5OTMsImV4cCI6MjA2OTg5OTk5M30.S-wQCng33hvIscgGyiqJqWXvAOnUass-v_TYikHqAtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});